# Generated by Django 2.0.3 on 2018-04-13 22:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0005_movies_music_television_visual'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movies',
            name='release_date',
            field=models.DateField(default=datetime.date(2018, 4, 13)),
        ),
        migrations.AlterField(
            model_name='television',
            name='first_air_date',
            field=models.DateField(default=datetime.date(2018, 4, 13)),
        ),
        migrations.AlterField(
            model_name='visual',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Author'),
        ),
    ]
